@startuml
title mymoney

class "账本" as account_book {
    String title; //账本名
    Date time; //创建时间
    ref owner; //创建人
}

class "账目" as account_item {
    ref debit; // 贷方账户
    ref credit; //借方账户
    Date time;// 发生时间
    number amount;//金额
    String title;//标题
    String remark;//备注
    Date timestamp; // 创建时间
    ref creator; // 创建人
}

class "标签" as tag {
    String name;//标签名
}

class "记账人" as recorder {
    String openId;
} 

class "账户" as account {
    String type; //账户类型: 资产、负债、收入、支出、净值
    String title; // 账户标题
    ref owner; //账户所有人
    Date time; //创建时间
}

account_book "1" -- "*" account_item
recorder "*" - "*" account_book
recorder "1" - "*" account_item
account_item "1" - "*" tag
account - account_item
@enduml