= 常用操作(Stream operations)
:api-doc: link:https://docs.oracle.com/javase/8/docs/api/index.html?java/util/stream/package-tree.html[官方API文档,window="_blank"]

根据{api-doc}，可以看到stream支持的所有操作，列举在<<appxa>>中。

这些操作分为两种类型：intermediate和terminal。

- intermediate: 各种能将返回类型为stream的操作连在一起形成pipeline的操作，比如filter,sorted,map,distinct等，
重要的是，intermediate并不会立即对数据做任何操作，这被称为##lazy##
- terminal: 会关闭stream的操作被称为terminal。它们从一个pipeline产生一个结果，比如List, Integer，甚至void。只有terminal操作被调用的时候，一个pipeline才会进行真正的处理。

.示例说明
====
[source, java]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8);
List<Integer> twoEvenSquares = 
    numbers.stream()
       .filter(n -> {
                System.out.println("filtering " + n); 
                return n % 2 0;
              })
       .map(n -> {
                System.out.println("mapping " + n);
                return n * n;
              })
       .limit(2)                                               <1>
       .collect(toList());
----
<1> limit(2)是一个``short-circuiting``；这样，仅仅处理部分stream，而无需所有。类似Boolean表达式中的AND操作符：只要一个expression为false，立刻返回，而无需计算剩余表达式。

[source, screen]
----
打印结果

filtering 1
filtering 2
mapping 2
filtering 3
filtering 4
mapping 4
----
====


[NOTE]
--
粗略来说，stream的操作属于filter-map-reduce模型，可以视作类似于fork-join。所以stream的操作中，组成pipeline的基本操作包括filter,find,match等操作属于intermediate，而forEach,max,toList等操作属于terminal。stream属于何种类别，都在附表A中进行了标注。
--

== intermediate操作

=== Filtering(过滤)

包括##filter##, ##distinct##, ##limit##和##skip##这4个操作


这一类操作对stream进行过滤之后，仍然返回stream。例如

.filtering示例
====
[source,java]
----
Stream.of("one", "two", "three", "four","three")
  .distinct()                                      <1>
  .filter(s -> s.contains("o"))                    <2>
  .skip(1)                                         <3>
  .limit(1)                                        <4>
  .forEach(System.out::println);
----
<1> *distinct*: Takes a predicate (java.util.function.Predicate) as an argument and returns a stream including all elements that match the given predicate
<2> *filter(Predicate)*: Returns a stream with unique elements (according to the implementation of equals for a stream element)
<3> *skip(n)*: Returns a stream that is no longer than the given size n
<4> *limit(n)*: Returns a stream with the first n number of elements discarded
====

=== Sorting(排序)

对stream元素进行排序，包括两个方法

- `Stream<T> sorted()`: sorted stream according to natural order
- `Stream<T> sorted(Comparator<? super T> comparator)`: sorted according to the provided Comparator


.sorting示例
====
[source,java]
----
Stream.of("one", "two", "three", "four","three")
  .sorted()                                        <1>
  .forEach(System.out::println);
  
Stream.of("one", "two", "three", "four","three")
  .sorted((o1, o2) -> o1.compareTo(o2))            <2>
  .forEach(System.out::println);
----
<1> 自然排序
<2> 提供排序算法
====

=== Mapping(映射)

映射操作分为map和flatMap两类，每种类型都包括3个快捷操作映射到Double,Long和Int类型。各自的方法签名如下：

map::
- ``<R> Stream<R> map(Function<? super T,? extends R> mapper)``
- ``DoubleStream mapToDouble(ToDoubleFunction<? super T> mapper)``
- ``IntStream mapToInt(ToIntFunction<? super T> mapper)``
- ``LongStream mapToLong(ToLongFunction<? super T> mapper)``
flatmap::
- ``<R> Stream<R> flatMap(Function<? super T,? extends Stream<? extends R>> mapper)``
- ``DoubleStream flatMapToDouble(Function<? super T,? extends DoubleStream> mapper)``
- ``IntStream flatMapToInt(Function<? super T,? extends IntStream> mapper)``
- ``LongStream flatMapToLong(Function<? super T,? extends LongStream> mapper)``

可以看出，map和flatMap的差别在于

map接受的Function类型参数做的事情是在stream的元素类型T和返回的stream元素类型R之间做了一个映射，这种映射是一对一的；  

而flatMap接受的Function类型参数所做的是在stream的元素类型T和返回类型R所构成的stream之间做了映射，很显然，这种映射是一对多的，也就是说，如果stream的元素类型是一个集合的话，通过flatMap，可以将这些集合展开(flat)。

.mapping示例
====
[source,java]
----
Stream.of("one", "two", "three", "four","three")
  .map(String::toUpperCase)
  .forEach(System.out::println);
  
Stream.of(Arrays.asList("MySQL", "Mongo", "PostgreSQL"),
  Arrays.asList("Java", "C++", "Swift"))
  .flatMap(element -> element.stream().filter(s -> s.length() > 5))
  .forEach(System.out::println);
----
====

可以看到，flatMap在过滤一对多的情况时，会非常有帮助。

=== Peek(查看)

这个操作和forEach对应，差别在于forEach是terminal操作，而peek属于intermediate。其方法签名为

- `Stream<T> peek(Consumer<? super T> action)`

根据API文档，这个操作主要用于调试，可以将元素打印出来，例如

.peek示例
====
[source,java]
----
 Stream.of("one", "two", "three", "four")
     .filter(e -> e.length() > 3)
     .peek(e -> System.out.println("Filtered value: " + e))      <1>
     .map(String::toUpperCase)
     .peek(e -> System.out.println("Mapped value: " + e))
     .collect(Collectors.toList());
----
<1> 如果这里换做forEach的话，后续操作是无法进行的
====

=== Sequential, Parallel, Unordered

这三个操作都继承自BaseStream。

[quote, 官方API文档]
--
Stream pipelines may execute either sequentially or in parallel. This execution mode is a property of the stream. Streams are created with an initial choice of sequential or parallel execution. (For example, Collection.stream() creates a sequential stream, and Collection.parallelStream() creates a parallel one.) This choice of execution mode may be modified by the BaseStream.sequential() or BaseStream.parallel() methods, and may be queried with the BaseStream.isParallel() method.
--

可以看出这三个操作均和stream的运行模式(execution mode)有关，sequential和parallel用于在并行和串行间切换。

而unordered则用于在并行情况下，提高运行效率

[quote, 官方API文档]
--
For sequential streams, the presence or absence of an encounter order does not affect performance, only determinism. If a stream is ordered, repeated execution of identical stream pipelines on an identical source will produce an identical result; if it is not ordered, repeated execution might produce different results.
For parallel streams, relaxing the ordering constraint can sometimes enable more efficient execution.

In cases where the stream has an encounter order, but the user does not particularly care about that encounter order, explicitly de-ordering the stream with unordered() may improve parallel performance for some stateful or terminal operations.
--


== terminal操作

只有terminal类型操作才会真正开启对stream的处理，此后，stream就无法再被其他操作使用了

=== Matching(匹配)

用于匹配判定，包括三个方法

- `boolean allMatch(Predicate<? super T> predicate)`: 全部匹配
- `boolean anyMatch(Predicate<? super T> predicate)`: 任意匹配
- `boolean noneMatch(Predicate<? super T> predicate)`: 无匹配

根据方法签名的名称，可以看出三个操作各自用途，根据predicate，返回true或者false，

.matching示例
====
[source,java]
----
System.out.println("result is : " + Stream.of("one", "two", "three", "four")
  .allMatch(s -> s instanceof String));
----
====

=== Finding(查找)

用来查找stream中的元素，包括两个操作

- `Optional<T> findFirst()`: 找到第一个
- `Optional<T> findAny()`: 找到任一个

可以看到，这两个操作均返回一个包装类型 ##Optional<T>##，是一种容器类，用来表示一个值是否存在(关于Optional类的说明，参见<<appxb>>)。

.finding示例
====
[source,java]
----
Optional<String> = 
Stream.of("one", "two", "three", "four")
  .findAny();                               <1>
----
<1> findAny操作属于一个short-circuiting 操作，即只要发现匹配，立刻终止操作并返回，而且出于性能考虑，这个操作返回结果是随机的。
====

=== Iterating(迭代)

遍历stream的每个元素，并执行操作，这个操作包括两个方法签名

- `void forEach(Consumer<? super T> action)`
- `void forEachOrdered(Consumer<? super T> action)`

一般认为，forEach 和常规 for 循环的差异不涉及到性能，它们仅仅是风格的差别

这是一个terminal操作，接受一个Consumer类型作为参数，可以对每个元素执行某种操作。和forEachOrdered的差别在于后者
##processes the elements one at a time##。

=== Reduction(消减)

reduction操作，又称作fold，接受一系列输入元素，通过重复应用某种组合操作(combining operation)，输出单一结果(summary result)，诸如给出一组数值的和或者最大值，或者将元素累计到一个list中。stream包括的reduction操作包括

. reduce
. collect
. sum
. max
. count

==== reduce

- `Optional<T> reduce(BinaryOperator<T> accumulator)`
- `T reduce(T identity, BinaryOperator<T> accumulator)`
- `<U> U reduce(U identity, BiFunction<U,? super T,U> accumulator, BinaryOperator<U> combiner)`

可以看到，reduce主要操作都由传入的二元操作符BinaryOperation决定。而这个BinaryOperation需要的实现来自BiFunction的接口方法apply，实际提供的是如何设定stream中前后两个元素的关联操作，然后将这种操作复制到所有元素上，例如

.reduce示例(一个参数)
====
[source,java]
----
Stream.of("one", "two", "three", "four")
  .reduce(new BinaryOperator<String>() {
    @Override
    public String apply(String s, String s2) {     <1>
      return s.concat("," + s2);                   <2>
      return s.concat(",");                        <3>
      return ","+s2;                               <4>
    }
  }).ifPresent(System.out::println);
----
<1> ``s``和``s2``分别代表上次计算结果和当前元素
<2> 输出``one,two,three,four``
<3> 输出``one,,,``。如果``s``没有被使用，那意味着始终没有上次计算结果
<4> 输出``four,``。如果``s2``没被使用，那意味着除了第一个元素，剩余元素都未被使用
====


.reduce示例(二个参数)
====
[source,java]
----
System.out.println(
Stream.of("one", "two", "three", "four")
  .filter(s -> s.length() > 3)
  .reduce("ccc", (s, s2) -> s.concat(",").concat(s2)));    <1><2><3>
----
<1> 具有两个参数的reduce操作，第一个参数是 `T identity`, 代表初始值
<2> 输出``ccc,three,four``
<3> 因为存在初始值，所以此方法返回值不需要包装类型``Optional``
====

而具有三个参数的reduce操作，根据官方文档

`combiner.apply(u, accumulator.apply(identity, t)) == accumulator.apply(u, t)`  
究竟是什么意思呢？


.reduce示例(三个参数)
====
[source,java]
----
System.out.println(
        Stream.of(1, 2, 3, 4)
                .reduce(0, (n1, n2) -> n1+n2, (p1, p2) -> p1*p2)        <1>
);
System.out.println(
        Stream.of(1, 2, 3, 4)
                .parallel()
                .reduce(0, (n1, n2) -> n1+n2, (p1, p2) -> p1*p2)        <2>
);
----
<1> 输出结果10，也就是说combiner完全没用
<2> 输出为24，在parallel模式下，工作的是combiner
====
 
      
==== collect

collect是很有用的操作，用于将元素收集到另一个不同的集合里作为结果，有两个方法签名

- `<R,A> R collect(Collector<? super T,A,R> collector)`
- `<R> R collect(Supplier<R> supplier,BiConsumer<R,? super T> accumulator,BiConsumer<R,R> combiner)`


它的概念如下
[quote, 官网文档]
--
Collector is specified by four functions that work together to accumulate entries into a mutable result container, and optionally perform a final transform on the result. They are:

- creation of a new result container (`supplier()`)
- incorporating a new data element into a result container (`accumulator()`)
- combining two result containers into one (`combiner()`)
- performing an optional final transform on the container (`finisher()`)

--

Java8提供多种内置collectors，可以通过Collectors的静态方法获得(参考<<appxc>>)，因此，大多数情况下使用第一种方法就可以了，比如

.collect示例
====
[source,java]
----
Stream.of("one", "two", "three", "four")
    .collect(Collectors.toList())
    .forEach(System.out::println);
----
====

==== max|min

都是一种特殊的reduction操作，根据指定的comparator排序。

- `Optional<T> max(Comparator<? super T> comparator)`
- `Optional<T> min(Comparator<? super T> comparator)`

.max示例
====
[source,java]
----
Stream.of("one", "two", "three", "four")
  .max((o1, o2) -> o1.compareTo(o2) > 0 ? -1:1)
  .ifPresent(System.out::println);
----
====

==== count

返回stream中元素数量

- ``long count()``


=== toArray

- ``Object[] toArray()``
- ``<A> A[] toArray(IntFunction<A[]> generator)``

toArray是实例方法——将当前stream转换为Array。例如

.toArray示例
====
[source,java]
----
Arrays.stream(
Stream.generate(() -> UUID.randomUUID().toString())
  .limit(5)
  .toArray()).forEach(System.out::println);
----
====

如果希望返回确定的类型，则要用到第二种方法，根据方法签名，可以看到IntFunction泛型是``A[]``，而接口IntFunction定义为

[source,java]
----
@FunctionalInterface                   <1>
public interface IntFunction<R> {
    R apply(int value);
}
----
<1> 函数接口

所以，可以这样使用

[source,java]
----
Person[] men = people.stream()
      .filter(p -> p.getGender() == MALE)
      .toArray(value -> new Person[value]);
----


更进一步简化为

[source,java]
----
Person[] men = people.stream()
      .filter(p -> p.getGender() == MALE)
      .toArray(Person[]::new);                 <1>
----
<1> 方法引用(Method Reference), java8特性之一


=== 其他操作

==== empty

- `static <T> Stream<T> empty()`

这个方法返回一个空的stream。很显然，其设计目的就是为了避免NPE，而在一些需要返回stream类型的地方作为填充对象使用的。

==== concat

- `static <T> Stream<T> concat(Stream<? extends T> a, Stream<? extends T> b)`

将两个stream拼凑起来，第二个stream的元素会跟在第一个stream的后面，如果两个stream都是ordered的，那么拼凑的stream也是排好序的，如果其中一个是parallel的，那么拼凑的stream就是parallel的。只有当拼凑的stream关闭的时候，两个输入stream才会关闭。