:doctype: article
:encoding: utf-8
:lang: zh
:toc: left
:numbered:

= kotlin handbook
wen

<<<

本手册用于快速检索kotlin的方方面面

<<<

== REPL(Read-Eval-Print Loop)

- Intellij
- kotlinc

== 和Java相比

=== if可做表达式

.if做表达式
====
[source, kotlin]
----
if (x > y) {
  println("x is greater than y")
} else {
  println("x is not greater than y")
}

println(if (x > y) "x is greater than y" else "x is not greater than y")
----
====

== type inferring(类型推断)

the compiler can infer the variable's type from the value that's assigned to it

== array

var myArray: Array<Byte> = arrayOf(1, 2, 3)

== function

- regular function
- single expression function

== class

- constructor

<<<

== 接口和类

. 声明
[source,kotlin]
----
interface Clickable {}             <1>

interface Clickable {              <2>
  fun click()                      <3>
}                                  

interface Clickable {              <4>
  fun click()
  fun showOff() = println(" I am clickable")  <5>
}                                  

class Button : Clickable {         <6>
  override fun click() = println("I was clicked")  <7>
}

open class RichButtong : Clickable {      <8>
  open fun disable()                      <9>
  final override fun click()              <10>
}       

abstract class Animated {                 <11>
}
----
<1> 空接口声明
<2> 含ASM的接口
<3> ASM
<4> 含默认方法的接口
<5> 接口默认方法: 不同于Java8,不需要``default``关键字
<6> 实现类: 用``:``而不是``extends``关键字
<7> 实现方法必须用关键字``override``，避免接口增加了实现类中同名的一个方法，导致实现类依然可以编译，但行为其实不正常的情况
<8> kotlin的类默认是final的，不同于Java，除非设计之初是允许继承的，则使用``open``关键字
<9> 方法也是如此，希望被重写的方法需要用``open``标记
<10> 重写方法具有传递性，也就是说自然可以被子类重写，除非使用``final``关键字阻止这件事
<11> 和Java一样，``abstract``关键字用来标示一个类是不能被实例化的


. 修饰符
[source,kotlin]
----
interface Clickable {}             <1>

interface Clickable {              <2>
  fun click()                      <3>
}                                  

interface Clickable {              <4>
  fun click()
  fun showOff() = println(" I am clickable")  <5>
}                                  

class Button : Clickable {         <6>
  override fun click() = println("I was clicked")  <7>
}

open class RichButtong : Clickable {      <8>
  open fun disable()                      <9>
  final override fun click()              <10>
}       

abstract class Animated {                 <11>
}
----

== 语法

.起始例子
====
[source,kotlin]
----
data class Person(val name: String,            <1>
    val age: Int? = null)                      <2>

fun main(args: Array<String>) {                <3>
    val persons = listOf(Person("Alice"),      <4>
      Person("Bob", age = 29)
    val oldest = persons.maxBy { it.age ?: 0 } <5>
    
    println("The oldest is: $oldest") }        <6>    
----
<1> 'data' class
<2> nullable type (Int?); default value for argument
<3> top-level function
<4> named argument
<5> lambda expression; "elvis" operator
<6> string template
====


=== Java中有的

=== Java中没有的

== 编码约定


.In maven
----
<properties>
  <kotlin.code.style>official</kotlin.code.style>
</properties>
----

== Mixing Java and Kotlin in one project

.在kotlin项目中引入java
----
直接创建java类，然后调用
----

.在java项目中引入kotlin
----
新建kotlin类，如果是在Intellij Idea中，会提示设置kotlin runtime
----

[appendix]
== Using Maven

.指定版本
----
<properties>
    <kotlin.version>1.3.61</kotlin.version>
</properties>
----

.扩展标准库
----
<dependencies>
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>${kotlin.version}</version>
    </dependency>
</dependencies>
----

.指定版本的扩展库
----
<dependencies>
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib-jdk8</artifactId>
        <version>${kotlin.version}</version>
    </dependency>
</dependencies>
----

[appendix]
== Hard keywords

. as
.. type cast: 会抛出异常的类型转换
.. alias for an import: 为import的类设置别名
. as? 不会抛异常的类型转换

