= George Washington

VOA Learning English presents America's Presidents.

Today we are talking about George Washington.

He was the first president of the United States. He served from 1789 to 1797.

But he had many other accomplishments, too.

He owned thousands of hectares of land in his home state of Virginia.

He was a famous general, who led the American colonists to freedom from British rule.

And he presided over the convention that created the U.S. Constitution.

For Washington, that was enough. He said he wanted to retire from public service and return home.

But the country’s new electors had other ideas. They wanted him to move to New York and invent the American presidency.

Washington accepted the job as his duty.

=== Washington as president

Washington was sworn in as president in 1789. At the time, a truly united states was still just an idea. Americans were unconnected groups. They came from different countries, had different religions, and spoke different languages. For example, a quarter of the people in the state of Pennsylvania spoke only German.

Doug Bradburn is the founding director of the Washington Library at Mount Vernon. He says when Washington took office, the country was “fragile.”

“The chances that it would even survive were probably very, very slim.”

Bradburn explains that Washington had to establish social and political unity. But the Constitution did not say how the president could do that.

So, Bradburn says, George Washington invented the job for all future presidents.

He established a group of advisors — called the cabinet—as well as the nation’s official money. He appointed a six-member Supreme Court. And he created the Department of Foreign Affairs, now called the State Department.

However, Washington said it was the president’s responsibility to set foreign policy. 

Historian Doug Bradburn explains that Washington established the president not just as a figurehead, but as a decision maker.

But he always used the Constitution as his guide.

“He wasn’t just trying to establish an office and then figure out a way to justify it, he was trying to work with his Constitution.”

=== Washington as a young man

George Washington was born in 1732 in the colony of Virginia. His father died when George was 11 years old. As a boy, he learned reading, writing and math. Then he worked as a land surveyor in western Virginia.

Historian Joseph Ellis points out that Washington did not have a formal education. Instead of going to college, Ellis says, Washington went to war. He fought against the French and Indians as a British Army officer.

That experience informed Washington’s world view. Ellis describes the first president as “a realist.” At the same time, Washington was a “very passionate man” with “extremely strong emotions.” He was known to get angry, but he showed his temper to only a few people.

Washington not only acted like a great leader – he looked like one. George Washington stood about 1.9 meters tall. That was a head taller than the average man of his time.

He was very strong, and very graceful. He was known as one of the best horseback riders and best dancers in Virginia.

But he had a problem: bad teeth.

Unlike his wife, Martha, who was known for her lovely smile, George Washington began losing his teeth in his twenties. When he was sworn in as president, he had only one tooth left.

=== Washington as a myth

Washington remains an important figure in the American imagination. Even today people tell stories about him.

One popular story, that he had wooden teeth, is not true. But he did wear dentures. They were made, in part, from hippopotamus ivory.

And he did not chop down a cherry tree as a child and then admit it by saying, “I cannot tell a lie.” In fact, historian Joseph Ellis says George Washington “lied many times.”

But it is true that as Washington became more famous, his reputation grew. People thought of him as a man who always did the right thing.

Joseph Ellis says even Washington understood people would look at his writings and judge him.

“Washington went from being a man to a monument. He was aware of the fact that he had a role to play and that all emerging nations need mythical heroes.”

Washington became very protective of his personal thoughts. His wife burned most of their letters.

Yet we know a little bit about George Washington’s thoughts from other writing. One of his regrets, he said, was that he had not done something to end slavery.

Like many plantation owners, Washington was a slave holder. More than 300 enslaved people lived on his property.

By the end of his life, Washington opposed slavery. He left a will ordering his survivors to free his slaves after his wife’s death.

Washington’s will became relevant sooner than he might have liked.

Three years after he finished his second term as president, Washington fell ill. He had been outside riding his horse on a cold, wet day. When he came home, he complained of a sore throat.

Over the next two days, his condition became worse. On December 14, 1799, he died in his bed, surrounded by his wife, enslaved maids, and friends. He was 67.

=== Washington’s legacy

Historian Joseph Ellis says one of the best things about George Washington was his ability to give up power. At the end of the Revolutionary War, General Washington returned his sword. And at the end of his administration, President Washington simply returned home.

“You could trust Washington with power because he was so conspicuously willing to give it up.”

Doug Bradburn says Washington was the right man at the right time. Bradburn, like many historians, calls George Washington the “indispensable man.”

In other words, Washington was essential to the American experiment in self-government. He made ideas about American freedom real, and he showed that even the president would operate under the rule of law.

I'm Kelly Jean Kelly.