== Andrew Jackson

VOA Learning English presents America’s Presidents.

Andrew Jackson, the seventh president, was unlike the earlier U.S. presidents.

His family was poor, he had little education, and he lived on what was then the western part of the country.

Jackson became nationally known in the early 1800s – first as a fighter against Native American tribes, and then as a general in the War of 1812 against the British.

His image as a military hero and man of the people made him a popular choice for the presidency.

But critics said Jackson did not accept any limits on his power.

He is also remembered for supporting slavery, and for forcing Native Americans from their homes.

== Wild child

Andrew Jackson’s parents were immigrants from Ireland. His father died in an accident before Andrew, the third and youngest son, was born.

When the American colonies entered a war of independence, Andrew and his two brothers fought against the British – although Andrew was too young to be a regular soldier.

Andrew’s oldest brother soon died.

Then Andrew and his other brother were both captured by British soldiers. One cut Andrew’s face, leaving a scar that remained his entire life.

But Andrew, unlike his brother, survived captivity.

A short time later, Andrew’s mother became sick and died. By age 15, Andrew Jackson had no living immediate family.

He had already stopped attending school, but taught himself enough to become a lawyer. He moved to what became Nashville, Tennessee, where he developed a successful law career.

In time, he bought land and slaves.

Jackson was tall and thin, with red hair and bright blue eyes. Sometimes Jackson was playful. He loved to dance, hold parties, and play games where he could win money.

Sometimes he was violent. He was known for getting angry easily. Jackson fought duels with several men. In one, he killed a man who insulted his wife.

Yet many people liked Jackson’s passionate, action-first personality. By the time the United States entered the War of 1812, Jackson had been a congressman, senator, and judge.

== Three nicknames

Jackson did not have any officially recognized military training. But during the War of 1812, he volunteered in the Tennessee militia and quickly took control of troops.

Many of his soldiers came to respect him. Jackson refused to give up, even when the government ordered the militia to disband. And, when some of the men wanted to leave, he threatened them with a gun.

Because he was uncompromising and strong as a tree, soldiers called Jackson “Old Hickory.”

A group of Creek Indians gave him another name. After he defeated them in battle, Jackson negotiated a treaty that punished both his Native American enemies and his Native American allies.

The treaty was more severe than the U.S. government had asked. In time, it forced the Creeks – as well as several other tribes – off their land.

The move was popular with many white settlers. It was less popular with the Creeks, who called Jackson “Sharp Knife.”

His best-known military operation was in New Orleans, Louisiana. A large, experienced army of British soldiers moved to attack. Jackson defended the city with a small group of untrained soldiers. His group included volunteers, free blacks, Creoles, Native Americans, and pirates.

Jackson’s ragtag troops not only defeated the British force, but suffered only a few losses. 

Jackson didn't know that the battle came after the British and Americans had already agreed to end the war. But his victory there gave many Americans a feeling of pride.

It also made Jackson famous. He became known across the country as the “Hero of New
Orleans.”

== A man of the people

Voters across the country supported Jackson, too. He was especially well-liked in the South and West.
Many Americans saw him as a man of the people. They believed his success came from experience and hard work, not wealth and family connections.

In the presidential election of 1824, Jackson received more popular and electoral votes than any of the other candidates. But, because no candidate had a majority, lawmakers in the House of Representatives decided the election.

Those lawmakers chose John Quincy Adams, the son of former president John Adams. They were persuaded, in part, because a leader in Congress, named Henry Clay, said Jackson did not have the temperament to be president.

Immediately after Quincy Adams won, he appointed Clay secretary of state.

The appointment angered Jackson. He believed Adams and Clay had entered into a “corrupt bargain.”

In the next presidential election four years later, Jackson defeated Quincy Adams in a landslide.

And in the presidential election after that, he crushed Henry Clay.

== A powerful president

Jackson wanted to be a powerful leader who controlled a limited federal government. But he wanted that government to have power over state governments.

For example, Jackson refused to let the state of South Carolina nullify, or ignore, a federal law that state offcials opposed. Jackson said if they failed to obey the law, he would consider them traitors and send in troops.

In time, South Carolina and Congress were able to reach a compromise on the law.

Jackson also refused to extend the charter of the National Bank. He believed the bank helped industrialists and businesses more than farmers and settlers. His move was popular with many voters – especially farmers and settlers.

But Jackson’s opponents warned against the bank veto. They disagreed with his economic plan, and they objected to how he had operated outside of Congress. Senators censured Jackson for acting as if he did not have to follow the law.

Jackson’s supporters fought back. They removed the official criticism from the Senate records.


== Indian Removal Act of 1830

Jackson vetoed more bills than the first six presidents combined. He actively worked for only one major law: the Indian Removal Act of 1830.

Jackson believed Native Americans occupied land that should belong to white settlers. He also thought Native Americans would be destroyed or lose their culture to white people anyway.

So he offered several tribes what appeared to be generous treaties to move onto land west of the Mississippi River.

But the treaties were often unfair or illegal. The tribes who accepted rarely received the benefits Jackson promised them. And some tribes, such as the Cherokees, simply refused to go.

Empowered by Jackson’s Indian Removal Act, U.S. government officials eventually forced 15,000 Cherokees off their land. They were made to march over 1,600 kilometers. About 4,000 died on the march. It is remembered as the “Trail of Tears.”

For white settlers, Jackson’s Indian removal policies resulted in over 100,000 square kilometers of new land to farm. Thousands of cotton planters moved west with their enslaved workers.

The Indian Removal Act served not only to aid an economic boom in cotton, but to spread slavery further in the United States. Jackson had no objections.

== Final years

In 1837, Jackson officially moved out of the White House – but he did not really leave the presidency. He advised the presidents who followed him from his home in Tennessee.

Jackson had particular influence over two future leaders: Martin Van Buren, his former vice president; and James Polk, who shared Jackson’s beliefs so closely that he was called “Young Hickory.”

Jackson’s beloved wife, Rachel, had died before he took office. They did not have any children together, but they raised two boys: a Native American orphan who died as a teenager; and a nephew, whom they called Andrew Jackson, Jr.

The younger Andrew Jackson and his wife lived with the former president in his final years.

He died in his bed at 78 of old wounds and old age. But his legacy remains very much alive.

== Legacy

Jackson changed the U.S. presidency. After him, presidential candidates had to show they could connect with voters, not just lawmakers.

He also increased the power of the chief executive. Jackson often questioned – or dismissed – the power of Congress, the Constitution, and the Supreme Court.

And, he began the custom of replacing experienced government officials with people whose main qualification was their loyalty to him.

Critics added to Jackson’s nicknames. They called him King Andrew, King Mob, or American Cesar. The opposition to Jackson led to a new political party called the Whigs.

Part of Jackson's legacy is the two major party system that exists in the U.S. today.

But those who loved Jackson really loved him. His humble beginnings, rise to power, and defense of the common man inspired them.

In the U.S., the name of Andrew Jackson is still often used as a positive symbol of American democracy.

I’m Kelly Jean Kelly.

