= Martin Van Buren

VOA Learning English presents America’s Presidents.

Today we are talking about Martin Van Buren. He was sworn in as the eighth president of the United States in 1837.

Van Buren had already been working for the White House for several years. He had been the secretary of state for President Andrew Jackson, and later his vice president.

Jackson asked his party, the Democrats, to nominate Van Buren as their presidential candidate in the 1836 election.

They agreed, and Van Buren won that election easily. But he did not win the next election. Or the next. Or the next.

== Presidency

In his inaugural speech in 1837, Van Buren noted that he was the first U.S. president to be born after the American Revolution.

He was also the first president who was not from a British family. His ancestors were Dutch.

He remains the only president – so far – who did not speak English as his first language. In his inaugural speech, Van Buren predicted better times for Americans.

But several days later, an economic crisis struck. The situation put the country in a depression that lasted for the rest of Van Buren’s term. It was one reason the president’s opponents called him “Martin Van Ruin.”

The depression was not Van Buren’s only problem. He also faced a dispute with Britain related to the border between the U.S. and Canada. The conflict nearly turned into war.

Historian Joel Silbey says most experts do not think Van Buren was a strong president. 

However, Silbey notes, Van Buren left an important legacy that still operates today: He created the modern U.S. political system.

== Early life

Van Buren’s political education began early.

His father was a farmer and operated a hotel at a small town in New York State. Lawmakers sometimes visited the hotel. By listening to them, the future president learned about politics.

Eventually, Van Buren studied in a law office and became a lawyer. In the first years of his career, he defended farmers who were fighting large plantation owners for their land. As a result, he developed a reputation for helping the common man.

Van Buren became a local official, and then a senator and governor of New York.

When he was 24, he married a young woman he had grown up with. But she died of tuberculosis after 12 years, leaving him with four sons.

Historian Joel Silbey says although Van Buren did not remarry, “he was known as quite charming among the ladies.”

== Political animal

Van Buren had a gift for politics – that is, developing relationships and forming alliances.

Historian Joel Silbey says most people who knew Van Buren liked him. He seemed warm and friendly. He tried to keep his work-related life and social activities separate. It was not unusual to see him exchange handshakes, smiles and jokes with men who were his political enemies.

His ability to make friends became a powerful tool. Before Van Buren, even lawmakers from the same political party operated independently.
They had their own beliefs, their own supporters, and their own allies. Van Buren brought them together.

First he identified people who followed the ideas of Thomas Jefferson: support for independent farmers and states’ rights. The group had become known as the Democratic Party (although it was in many ways different from the Democratic Party of today).

Van Buren organized meetings for Democrats to talk about their political beliefs. He persuaded them to support the same policies – at that time, the policies of Andrew Jackson.

Sometimes, Van Buren helped people who supported Jackson’s policies. He gave them government jobs.

Van Buren also used a series of meetings to choose one presidential candidate for the party. If this process seems clear-cut, it was not at the time. During the election of 1824, for example, a single party had four separate candidates for president, one for each part of the country.

Van Buren’s system eventually gave rise to the national conventions that major U.S. parties use today to nominate their candidates.

== Model campaigner

Van Buren also helped create the modern political campaign. In the 1820s, he saw that many state constitutions were lifting some of their voting restrictions. As a result, states were giving more white males the right to vote. (Women and most African-American men were still largely prohibited from voting.)

Historian Joel Silbey says Van Buren wanted to bring these new voters into the Democratic Party. He decided to improve on the methods that other, smaller groups had used: campaign events, speeches, and organized efforts to bring people to vote on Election Day.

Silbey explains that these efforts to persuade and energize voters were new to national politics. Now they are some of the major features of political campaigns.

== Live by the sword, die by the sword

In the election of 1840, Van Buren sought a second term as president. This time his opponents used Van Buren’s political techniques against him.

Silbey says the new opposition party, called the Whigs, used popular speeches and events to portray Van Buren as a failed president.

Crowds shouted, “Mattie Van is a used-up man!” In other words, he no longer had any power or effect in government.

Critics also made fun of Van Buren’s fine-looking, even fussy clothes. They portrayed him as a rich, elite candidate. They compared him unfavorably to their candidate, a military hero named William Henry Harrison.

Yet it was Van Buren who had come from a poor family, and Harrison from a wealthy one. Even so, Van Buren lost the election of 1840.

Four years later, Van Buren again sought the presidency. This time, even Andrew Jackson did not support him. Instead, Jackson backed a man who supported the seizure of Texas and expanding slavery: James Polk.

But Van Buren did not permit those defeats to stop his political career. He ran again in the presidential election of 1848.

This time, Van Buren withdrew from the Democratic Party he had helped build. He ran instead as the candidate of a new, anti-slavery party, called the Free Soilers.

But even Van Buren’s political skills could not persuade voters. He did not win a single state.

After losing this final presidential election, Van Buren finally retired. He spent time with his children and grandchildren, traveled, and wrote about his life.

At 79 he died of heart failure.

I’m Kelly Jean Kelly.