= William Henry Harrison

VOA Learning English presents America’s Presidents.

Today we are talking about William Henry Harrison. Although he was elected in 1840, many Americans still remember his catchy campaign slogan: “Tippecanoe and Tyler, too.” 

“Tyler” referred to John Tyler, Harrison’s partner on the ticket. In other words, Harrison was the candidate for president, and Tyler was the candidate for vice president.

That seems straightforward enough. But “Tippecanoe”? That was Harrison’s nickname. It came from a battle he had fought nearly 30 years before the presidential campaign.

At that time, Harrison led troops against an alliance of Native American tribes. The alliance was fighting white American settlers who were taking native people’s territory.

Harrison and his men wanted to prevent the alliance from getting the supplies and warriors it needed to fight a long war. They planned to attack an important Native American base in what is today the state of Indiana.

But Native American warriors attacked first. They struck at dawn, when Harrison’s men were still sleeping in a camp near the River Tippecanoe.

The battle was confused and bloody. Many fighters on both sides died. After several hours, Harrison’s troops pushed the Native American fighters away from the camp.

It was not really clear who won, but Harrison declared victory.

His presidential campaign reminded voters about the battle. The nickname “Tippecanoe” suggested Harrison was a simple yet tough westerner who would fight for white Americans.

But that image of Harrison was not entirely true.

== Early life

Harrison did not come from a simple, western family.

Instead, he was the youngest child of a wealthy family from the southern state of Virginia. The Harrisons were active in the politics of the young nation. His father signed the Declaration of Independence and became the governor of Virginia.

Young William Harrison received a good education. But he did not want to become a doctor or lawyer. He joined the military instead.

Harrison succeeded quickly as an Army officer. He earned a reputation as an able leader in fights against Native Americans.

Harrison became the governor of what was known as Indiana Territory.

In that job, he persuaded Native Americans to enter into treaties that sold their land to the U.S. government – often for very little money.

Harrison’s insistence on securing land for white settlers was one reason Native American tribes formed an alliance against the United States. A member of the Shawnee tribe, Tecumseh, was one of their most prominent leaders.

It was Tecumseh’s men who fought against Harrison in the Battle of Tippecanoe.

Tecumseh’s men clashed again with Harrison during the War of 1812 at a battle in Ontario, Canada near the River names.

In that battle, both the British and Native Americans were clearly defeated. Tecumseh was killed.

After that, the Native American alliance fell apart. And Harrison became famous again.

== Political career

Although Harrison was a well-known fighter against Native Americans, he could not find lasting success as a politician.

He served briefly in both the House of Representatives and the Senate, but he did not stay in those positions long.

He struggled with debt. His home in Indiana was very expensive. He also had to provide for his ten children.

The emotional cost of his family was also high: only four of his children lived past the age of 40.

In 1836, Harrison’s fortunes seemed to change. A new party, called the Whigs, looked to him as a presidential candidate.

The Whigs strongly opposed President Andrew Jackson and his policies. They did not want Jackson’s vice president and right-hand man, Martin Van Buren, to become president. But they understood that Jackson was very popular with everyday Americans.

So the Whigs thought that Harrison – a military hero from the west, just as Jackson was – would appeal to voters. (At the time, voting was limited mostly to white men.)

The Whigs nominated Harrison as one of their candidates.

Harrison did well – but not well enough. Van Buren won the 1836 election.

But the next election belonged to Harrison.

His campaign developed that memorable song about “Tippecanoe and Tyler, too.” Supporters also turned an insult against Harrison into an advantage.

Harrison’s opposition said he would be happy to spend the rest of his life just sitting in a log cabin and drinking hard cider – an alcoholic drink made from apples.

The opposition wanted to suggest that Harrison was not really interested in becoming president and working hard for the American people.
But Harrison’s supporters used the images of a log cabin and hard cider to portray Harrison as a humble man who could relate to common Americans.

The plan was a success: Harrison won the election. 

== A surprising turn of events

At 68, Harrison was the oldest person yet to take office.

On his Inauguration Day, he reportedly wanted to show that he was strong enough to serve as president by delivering a very long speech without wearing a coat or hat.

Several weeks later, Harrison became sick. He complained of many problems: anxiety, fatigue, and pain in his stomach.

His health grew worse and worse.

One month after he was sworn-in, Harrison died. It was the first time in the country’s history that a president had died in office.
The event raised many questions about who would become president. That question is answered in the next episode of this series.

For future generations, it also raised a question about what Harrison died of. The traditional story is that his long inaugural speech led to a fatal pneumonia.

But researchers in 2014 proposed a different reason.

Jane McHugh and Philip Mackowiak wrote in the New York Times that, while Harrison was in office, Washington, DC did not have a good sewer system. Human waste “simply flowed onto public grounds a short distance from the White House.”

The researchers conclude that Harrison probably died from problems related to drinking dirty water in the president’s house.

So, for Harrison, winning the White House may not have been good fortune at all. 

I’m Kelly Jean Kelly.