= John Tylor

VOA Learning English presents America’s Presidents.

Today we are talking about a vice president. John Tyler was William Henry Harrison’s partner on the ticket in the 1840 election; he was the “Tyler” of the campaign slogan “Tippecanoe and Tyler, too.”

But only one month into his term as president, Harrison unexpectedly died. He was the first U.S. president to die in office. Today, Americans accept that when that happens, the vice president becomes the president. But in 1841, no one really knew what to do.

So people turned to the Constitution.

It said if the president is removed from office, or if he dies, resigns, or is not able to perform his duties, his power and responsibility is given to the vice president.

But the meaning of those words was unclear. Did the vice president really become the president, or did the vice president just act like the president?

The Constitution may not have been clear, but John Tyler was. He claimed that, after Harrison’s death, he really was the president.

Tyler made sure he was quickly sworn-in. He answered only to the title “president.” He even refused to open letters that were sent to “Acting President Tyler.”

Eventually, Americans accepted John Tyler was the nation’s 10th president.

But some Americans were not happy about that fact. During his presidency, all but one of Tyler’s cabinet advisors resigned, and members of his own party tried to impeach him.

== Early life


Tyler was from the southern state of Virginia, home to live earlier U.S. presidents. Like many of the leaders before him, he was a lawyer from an upper class family who owned slaves. He strongly supported the power of the states against the federal government, expansion of slavery, and rule by a small, elite group.

But the United States was starting to change. For example, President John Quincy Adams had proposed creating a national system of roads. The Missouri Compromise of 1820 limited slavery in new states in the northwest. And in the 1830s, many white men who did not own property earned the right to vote.

In other words, the U.S. was becoming more national, abolitionist, and equal.

Tyler resisted these changes. He fought against them as a member of the U.S. House of Representatives, a governor of Virginia, and a senator.

His fight reached a crisis during the presidency of Andrew Jackson. The two men belonged to the same party, the Democratic Party. However, Tyler hated Jackson’s populist policies and use of presidential powers against the states.

In the middle of the 1830s, Tyler joined with several other political leaders to create a new, anti-Jackson party. They were called the Whigs.

== Presidency

The new Whig party badly wanted to win the 1840 presidential election against Jackson’s right hand man, Martin Van Buren. They proposed John Tyler as the party’s vice presidential candidate because they hoped he would appeal to southern voters.

The Whigs succeeded. Tyler and Harrison won the election. The new party expected that they would be able to achieve many of their policy goals.

But then Harrison died, and Tyler unexpectedly became president. Tyler kept Harrison’s cabinet of top advisers. But he did not accept their advice.

Whig lawmakers presented bill after bill to Tyler, but he failed to support the measures. He believed they gave too much power to the federal government over the states.

In anger, all but one of Tyler’s cabinet members resigned.

Then Whig leaders officially declared that Tyler was no longer part of their group. The following year they even moved to impeach him.

He became known as a president without a party.

Tyler was able to achieve one major political act, however. Three days before he left office, he signed the law that made Texas a state.

Perhaps wisely, Tyler withdrew from the next presidential election.

He eventually withdrew even his support for the federal government. He became a leader in the movement for Southern secession.

In other words, he believed the Southern states had the right to separate from the North and leave the Union. In time, the separation between the South and North would lead to the Civil War.

== Family

Tyler was an unusual president. He took office in an unusual way, and he took the unusual step of vetoing legislative action proposed by his own party.

His family life has other unusual details. Tyler was the first president to get married while in office. He was the president with the most children. And two of his grandchildren remained alive until well into the 21st century.

In 1844, Tyler married Julia Gardiner. She was his second wife. His first wife, Letitia, had died two years earlier.

John and Letitia Tyler had eight children together. Since Julia Gardiner Tyler was 24 years old -- 30 years younger than her new husband -- the two had plenty of time to have another seven children.

And, because one of their sons had children in the 1920s, two of Tyler’s grandchildren are still alive as of early 2017.

== Legacy

Tyler is not remembered as a good president. But he is remembered for establishing a precedent – a way of doing something that other people have followed.

The Tyler precedent permitted the peaceful of transfer of power from president to vice president in 1841. And it eased the transition after other presidents have died since then.

In 1967, the Constitution was even changed to clarify what Tyler had claimed all along: when the president dies, the vice president becomes the new chief executive.

I’m Kelly Jean Kelly.