= Zachary Taylor

VOA Learning English presents America’s Presidents.

Today we are talking about Zachary Taylor, the 12th president. He took office in 1849.

Taylor had some things in common with earlier presidents.

Like six others before him, he was born in Virginia.

Like George Washington and Andrew Jackson, Taylor was a war hero.

And, like William Henry Harrison, he died in office.

But Taylor brought at least one special trait to the presidency. Although he was officially elected as a member of the Whig party, Taylor considered himself an independent.

== Early life

When Zachary Taylor was a baby, his family left Virginia. They moved west, to a tobacco plantation in Kentucky.

There, the Taylors were financially successful. By the time Zachary was a young man, his family owned a number of enslaved people and over 4,000 hectares of land.

Taylor took possession of some of his family’s land. He also had cotton plantations in the southern states of Mississippi and Louisiana. He, too, depended on enslaved people to do most of the work.

But Taylor was unlike many wealthy farmers in the South. He had always wanted to be a soldier. When Taylor was 24 years old, he became an officer in the U.S. Army.
    
Shortly after, he married Margaret Smith. In time, they had five daughters and one son. But Taylor directed most of his attention to his military career.

For about 20 years, he tried to keep peace between Native American tribes and white Americans. Sometimes the job meant leading attacks against Native Americans. At times, it meant defending their lands from white settlers.

In either case, his public standing as a good soldier grew. His troops called him “Old Rough and Ready” because he was willing to fight – and suffer – alongside them.

Then, in the Mexican-American War of the 1840s, Taylor became really famous. He led U.S. troops to victory in several major battles, including ones at Monterrey and Buena Vista.

In a well-known story, the powerful Mexican general Santa Anna surrounded Taylor and his small number of troops. Santa Anna sent a message demanding that they surrender. Taylor reportedly said: “Tell him to go to hell.”

The two sides clashed the next morning. Santa Anna had about three times the men that Taylor had. Yet, by late that day, Taylor’s soldiers had defeated Santa Anna’s.

Taylor’s success as a general helped the United States win the war against Mexico. In the Treaty of Guadalupe Hidalgo, Mexico agreed to give up claims to or sell to the U.S. more than 1.3 million square kilometers of its lands, including what are now the states of Texas and California.

But the new lands almost immediately caused problems. 

== Campaign of 1848

At the time of the next U.S. presidential election, public opinion in the country was severely divided. The issue was whether to permit slavery in the new lands won at the end of the war with Mexico.

In general, Northerners opposed expanding slavery. In general, Southerners supported it.

To appeal to both these groups, the major parties at the time looked to Taylor to be their candidate for president.
   
The Democrats and the Whigs reasoned that Taylor was already well-known and well-liked. Historian Michael Holt said in 1848, Taylor was “the most popular man in America.”

But Taylor was not really political. He called himself an independent. He shared some beliefs with both major parties at the time. But mostly he wanted to keep the nation together.

In the end, he agreed to be the candidate of the Whig Party. During the campaign, he did not take a stand on any of the major issues. His fame as a military general carried him into the White House.

== Presidency

The truth was that Taylor did have an opinion on slavery: He did not want to expand it, especially in areas that did not support cotton or sugar farms.

So, once in office, he proposed a change to the rules about how new territories would become states. The change would let white, American, male settlers in California and New Mexico decide whether they wanted slavery. Then, those areas could enter the Union immediately as states.

Taylor aimed to quiet the debate about slavery. But his idea angered almost everybody. Some U.S. lawmakers believed the president had cut them out of the decision.

Northerners said Taylor’s proposal did not go far enough: It did not solve some of the other issues related to slavery.

And Southerners realized that settlers in California and New Mexico would almost surely reject slavery, and give free states a majority in Congress.

In one dramatic incident, some South Carolina officials called a meeting to discuss withdrawing from the Union. In answer, Taylor threatened to hang them.

But before Taylor or his idea could get too far, the president became sick.

The story is that he attended outdoor celebrations to mark the nation’s birthday, July 4. then he went for a walk. The weather was very hot. To cool off, Taylor ate uncooked fruit and drank iced milk.

That night he told others about pain in his stomach. Five days later, he was dead.

His doctor wrote that Taylor died of cholera morbus -- a general term for severe digestive problems.

A few people thought he might have been poisoned. The suspicion remained until 1991, when medical officials examined Taylor’s remains. They confirmed that he died of natural causes.

A more recent study offers more details. Jane McHugh and Philip A. Mackowiak say that Taylor was a victim of the same problem that killed presidents William Henry Harrison and James Polk: dirty water in the White House.

== Legacy

Taylor’s death, while unfortunate, did not cause a political crisis. John Tyler had already established the rule that, if a president dies in office, the vice president becomes president.

But Taylor’s death did likely change the direction of history. His replacement, Millard Fillmore, did not try to hold the Union together by force. Instead, he joined with politicians who wanted to compromise on the issue.

The compromise legislation delayed but did not really settle the debate. In time, the division between North and South led to the American Civil War.

And members of Taylor’s own family became linked to the states that withdrew from the Union.

One of his daughters had married Jefferson Davis, who became the president of the Confederacy.

I’m Kelly Jean Kelly.