= Millard Fillmore

VOA Learning English presents America’s Presidents.

Today we are talking about Millard Fillmore, the 13th president of the United States.

Fillmore is also likely the least remembered president. He has been called “uninspiring” and having only “some competence.”

But Fillmore provided an example of the American dream come true. He rose from a poor family to become a wealthy man. He was elected to Congress four times and nominated for vice president under Zachary Taylor. When Taylor unexpectedly died in office in 1850, Fillmore took his place.

== Early life

Other presidents’ campaigns, such as Andrew Jackson’s, had spoken proudly of their candidates’ modest beginnings. William Henry Harrison’s supporters especially linked him with the image of a simple house called a log cabin – even though William Henry Harrison was a wealthy man.

But Millard Fillmore really was born in a log cabin. His family was poor. They raised him and his seven brothers and sisters in a rural part of New York State.

Fillmore did not receive much education as a child. However, he was very interested in learning – so interested that he fell in love with his teacher, Abigail Powers.

The two married after he launched his career as a lawyer. They had two children, a son and a daughter.

Millard Fillmore soon entered politics. He won elections to the New York State Assembly, and then to the U.S. House of Representatives.

After eight years in Washington, DC, Fillmore returned to New York. He failed to be elected governor, but succeeded to become comptroller of New York. In other words, he oversaw the state’s finances.

At that time, Americans were preparing for another presidential election. President James Polk was retiring from the White House after only one term, as he had promised.

The opposition party, the Whigs, nominated Zachary Taylor as their presidential candidate.

Taylor, a popular war hero from the South, owned slaves. But the Whigs realized that many anti-slavery voters in the North would not support Taylor. Party leaders were looking for someone to balance the ticket – a Northerner voters would consider a friend of business.

They found Millard Fillmore.

In 1847, the Whigs nominated Fillmore as Taylor’s vice president. The two men had never met. And, when they did meet, they did not like each other very much.

Taylor was short-legged, poorly educated, and rarely seemed concerned about his physical appearance. Fillmore was taller, learned, and elegant. Their personalities did not fit together any better than their appearances did.

But a majority of voters liked them. The Whigs won the election, and Fillmore returned to Washington.

== A vice president without a voice

As vice president, Millard Fillmore was the leader of the Senate. But President Taylor did not seek his advice on the major political issue of the day.

At the time, both lawmakers and the public were debating whether the government should – and could – ban slavery in the territories the U.S. had gained after the war with Mexico.

In general, Northerners did not want to permit slavery in new states. But many Southerners did. The debate was so heated that one of the Southern states, South Carolina, threatened to leave the Union.

President Taylor did not want to expand slavery. To restrict it, he proposed a change to the rules so California and New Mexico could enter the Union quickly as slave-free states.
 
But before Taylor’s idea could get too far, he became sick. Fillmore learned the president was not well and prepared for the worst. It came.

Taylor died after being in office for only 16 months. The following day, Fillmore was sworn- in as president.

== Presidency

One of Fillmore’s first acts as president was to show where he stood on the slavery issue. He appointed a man who opposed Taylor to secretary of state.

That man, Daniel Webster – and others – wanted to pass a compromise bill on slavery. With Fillmore’s support, they succeeded.

The Compromise of 1850 included several measures related to slavery. Two measures limited it: California was admitted as a free state, and the slave trade in Washington, DC ended.

On the other hand, New Mexico and Utah were left open to slavery, and both the federal government and ordinary citizens were required to return suspected escaped slaves to their owners. That last measure, the Fugitive Slave Act of 1850, targeted even free African- Americans and enslaved people who had escaped to free states.

The Compromise aimed to end the confflict between pro-slavery and anti-slavery forces. But neither side was really satisfied.

And President Fillmore did not help matters. He was personally opposed to slavery. However, he did not act on his beliefs. Instead, he tried to keep the South in the Union by strongly enforcing the Fugitive Slave Act.

By the end of Fillmore’s three years in the White House, many members of his Whig party were angry with him. Party leaders did not nominate him again for the next election.

But their chosen candidate was not successful either. Fillmore turned out to be the last Whig president.

== Legacy
 
The end of Fillmore’s presidency included difficulty in his private life, too. His wife, Abigail, became sick on the day the next president was sworn-in. She died within a month. Soon after, Fillmore’s daughter died, too.

To help deal with their loss, Fillmore tried to stay active in politics. In the presidential election of 1856, Fillmore served as the candidate for a new party -- the Know-Nothing Party.

The Know-Nothings were strongly opposed to immigration. They especially wanted to limit the number of Irish Catholics who could come to the United States.

Fillmore did not agree with the party’s anti-immigration policies. But he did not have a chance to put his opinions into policy. Fillmore finished third out of the three major candidates in the election.

After that loss, he finally retired to the city of Buffalo, New York. There, Fillmore married a second time -- to a wealthy widow named Caroline McIntosh. He remained an important argure in the city’s charities and other causes.

But the political situation in the country grew only more intense. Americans continued to be divided over the issue of slavery. Fillmore’s time in office and his compromise bill may have delayed but did not stop the American Civil War.

I’m Kelly Jean Kelly.